apiVersion: v1
kind: Namespace
metadata:
  name: hospital
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: hospital
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "Swanny00..1119"   # 실제 운영 전에 반드시 교체
  MYSQL_DATABASE: "hospital"
  MYSQL_USER: "hospital_app"
  MYSQL_PASSWORD: "Swanny00.."          # 실제 운영 전에 반드시 교체
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: was-config
  namespace: hospital
data:
  MYSQL_HOST: "mysql-0.mysql-svc.hospital.svc.cluster.local"
  MYSQL_PORT: "3306"
  TZ: "Asia/Seoul"
  FLASK_DEBUG: "false"
